name: Goose

on:
   pull_request:
      types: [opened, synchronize, reopened, labeled]

permissions:
   contents: write
   pull-requests: write
   issues: write

env:
#    PROVIDER_API_KEY: ${{ secrets.REPLACE_WITH_PROVIDER_API_KEY }}
   PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
   goose-comment:
      runs-on: ubuntu-latest

      steps:
         - name: Check out repository
           uses: actions/checkout@v4
           with:
               fetch-depth: 0

         - name: Gather PR information
           env:
             GH_TOKEN: ${{ github.token }}
           run: |
                  {
                  echo "# Files Changed"
                  gh pr view $PR_NUMBER --json files \
                     -q '.files[] | "* " + .path + " (" + (.additions|tostring) + " additions, " + (.deletions|tostring) + " deletions)"'
                  echo ""
                  echo "# Changes Summary"
                  gh pr diff $PR_NUMBER
                  } > changes.txt

         - name: Install Goose CLI
           run: |
                  mkdir -p /home/runner/.local/bin
                  curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh \
                  | CONFIGURE=false INSTALL_PATH=/home/runner/.local/bin bash
                  echo "/home/runner/.local/bin" >> $GITHUB_PATH

         - name: Configure Goose
           run: |
                  mkdir -p ~/.config/goose
                  cat <<EOF > ~/.config/goose/config.yaml
                  GOOSE_PROVIDER: openai
                  GOOSE_MODEL: gpt-4o
                  keyring: false
                  EOF

         - name: Create instructions for Goose
           run: |
                  cat <<EOF > instructions.txt
                  Create a summary of the changes provided. Don't provide any session or logging details.
                  The summary for each file should be brief and structured as:
                  <filename/path (wrapped in backticks)>
                     - dot points of changes
                  You don't need any extensions, don't mention extensions at all.
                  The changes to summarise are:
                  $(cat changes.txt)
                  EOF

         - name: Test
           run: cat instructions.txt

         - name: Run Goose and filter output
           run: |
                  echo '### :goose: Goose Summary' > pr_comment.txt
                  set -o pipefail
                  export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
                  goose run --instructions instructions.txt | tee goose_output.log
                  cat goose_output.log | \
                  sed -E 's/\\x1B\\[[0-9;]*[mK]//g' | \
                  grep -v "logging to /home/runner/.config/goose/sessions/" | \
                  grep -v "^starting session" | \
                  grep -v "^Closing session" | \
                  sed 's/[[:space:]]*$//' | \
                  grep . \
                  >> pr_comment.txt

         - name: Post comment to PR
           env:
             GH_TOKEN: ${{ github.token }}
           run: |
                  gh pr comment $PR_NUMBER --body-file pr_comment.txt
